### ISSUE TITLE
Interactive transliteration demo

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript.com#2]
Linking to the JS version or the Lambda API

_Originally posted by @strogonoff in https://github.com/interscript/interscript.com/issues/1#issuecomment-669760740_

**Comment by strogonoff** [comment]
Almost done but blocked by https://github.com/interscript/interscript-api/issues/10 (cc @ronaldtse)

**Comment by ronaldtse** [comment]
@strogonoff two important issues:

1. Many systems are missing from the live demo, e.g. `bgna` systems. These are all available via the API:
<img width="871" alt="Screen Shot 2020-09-05 at 3 17 36 PM" src="https://user-images.githubusercontent.com/11865/92300120-f0a39880-ef8a-11ea-9052-f91f14c56eda.png">

2. For example, the `cn` authority with `pinyin` system is not even present in the Interscript API. Where does it come from?

The real map doesn't even have the word `cn`:

https://github.com/interscript/interscript/blob/master/maps/sac-zho-Hans-Latn-1979.yaml

<img width="960" alt="Screen Shot 2020-09-05 at 3 18 43 PM" src="https://user-images.githubusercontent.com/11865/92300142-1761cf00-ef8b-11ea-8676-9df4b4166d20.png">

**Comment by strogonoff** [comment]
@ronaldtse 

Systems were hard-coded[0] while API was under development and were left in that state.

To fix this, the following is needed:

* Update [LiveDemo](https://github.com/interscript/interscript.com/blob/master/src/containers/Landing.tsx#L79) component to get a list of systems using API (using `axios`, see [another API call for an example](https://github.com/interscript/interscript.com/blob/master/src/containers/Landing.tsx#L112). This should happen in `useEffect()` in the beginning of component lifecycle. Make sure the list is in the same format as in [0], and pass it as a prop to `SystemSelector`.

* Update [SystemSelector](https://github.com/interscript/interscript.com/blob/master/src/components/SystemSelector.tsx#L41) component to accept a conversion systems as a list via a prop (instead of having them hard-coded[0]).

I can take it later or perhaps someone wants to try a React task, this could be a good first one (I’ll review the PR).

[0] See https://github.com/interscript/interscript.com/blob/master/src/components/SystemSelector.tsx#L41

**Comment by strogonoff** [comment]
(Un-assigning for now until I take it later if no one else does)

**Comment by ronaldtse** [comment]
@webdev778 is handling this now.
